apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-gzxl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-gzxl
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-gzxl
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-gzxl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-gzxl
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-yyfg-tenant/rhtap-demo-app/hacbs-test-project-gzxl@sha256:5027086ae03d82028005113af404889de8f2ee0885800a3def2888fd0e5b56d5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
